apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    user: default
    isDefault: true
    editable: false
    version: 2
    jsonData:
      host: clickhouse
      defaultDatabase: analytics
      port: 8123
      protocol: http
    secureJsonData: {}
